Algoritmo "semnome"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/4/2020
Var
// Seção de Declarações das variáveis 
   n: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Leia(n)
se n > n/2 -1 entao
   Escreva(n/2 , ", x")

   senao
        Escreva(3*n+1, "y")
fimse

Fimalgoritmo
