Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/5/2020
Var
// Seção de Declarações das variáveis 
   x : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva("Digite o valor de (X): ")
   leia(x)
   x <- -x+2*(3-5)
   escreva("O valor de X é: ", x)

Fimalgoritmo